/**
 * Publishes contract ABIs into the web package.
 *
 * Phase 8 needed a way for `packages/web` to reach the ABIs without importing
 * across the workspace boundary. Importing `packages/contracts/artifacts/**`
 * from Next.js would drag Hardhat's whole artifact shape (bytecode, link
 * references, source maps) through Turbopack for no benefit, and TypeChain's
 * output is ethers-v6 flavoured while the frontend is on viem.
 *
 * So this does what `deploy.ts` already does for addresses: reads the Hardhat
 * artifacts and writes one generated, hand-edit-free TypeScript module. Only
 * the `abi` field is copied, and it is emitted `as const` so viem can infer
 * argument and return types from it.
 *
 * Run after `hardhat compile`, via `npm run abis` in this package.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const ARTIFACT_ROOT = path.join(__dirname, "..", "artifacts", "contracts");
const OUTPUT = path.join(__dirname, "..", "..", "web", "lib", "contracts", "abis.ts");

/**
 * Which artifacts the frontend is allowed to see, and the export name each
 * gets. Deliberately a whitelist: the web app has no business holding the
 * ABI of a contract it never calls, and an accidental new artifact should
 * not silently widen the generated module.
 */
const TARGETS: { artifact: string; exportName: string }[] = [
  { artifact: "SortisPool.sol/SortisPool.json", exportName: "sortisPoolAbi" },
  { artifact: "SortisDraw.sol/SortisDraw.json", exportName: "sortisDrawAbi" },
  { artifact: "SortisFaucet.sol/SortisFaucet.json", exportName: "sortisFaucetAbi" },
  { artifact: "token/ConfidentialUSDT.sol/ConfidentialUSDT.json", exportName: "confidentialUsdtAbi" },
  { artifact: "yields/MockYieldSource.sol/MockYieldSource.json", exportName: "mockYieldSourceAbi" },
];

interface HardhatArtifact {
  contractName: string;
  abi: unknown[];
}

function readAbi(relativePath: string): HardhatArtifact {
  const file = path.join(ARTIFACT_ROOT, relativePath);
  if (!fs.existsSync(file)) {
    throw new Error(`Artifact not found: ${file}\nRun "npm run compile" in packages/contracts first.`);
  }

  const artifact = JSON.parse(fs.readFileSync(file, "utf8")) as HardhatArtifact;
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Artifact has no abi array: ${file}`);
  }

  return artifact;
}

function main() {
  const blocks: string[] = [];

  for (const target of TARGETS) {
    const artifact = readAbi(target.artifact);
    // Two-space JSON keeps the generated file reviewable in a diff. Prettier
    // is not run over generated output, so the indentation here is the
    // indentation that ships.
    const body = JSON.stringify(artifact.abi, null, 2)
      .split("\n")
      .map((line, index) => (index === 0 ? line : `  ${line}`))
      .join("\n");

    blocks.push(`/** ${artifact.contractName}, generated from the Hardhat artifact. */
export const ${target.exportName} = ${body} as const;`);
  }

  const header = `// Generated by packages/contracts/scripts/generate-abis.ts. Do not edit by hand.
//
// Regenerate with "npm run abis" in packages/contracts (after "npm run compile"),
// or "npm run contracts:abis" from the repo root. Only the ABI is copied here:
// bytecode stays in the contracts package.
`;

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, `${header}\n${blocks.join("\n\n")}\n`, "utf8");

  console.log(`Wrote ${OUTPUT}`);
  for (const target of TARGETS) {
    console.log(`  ${target.exportName}`);
  }
}

main();
