import type { Metadata } from "next";
import { formatTokenAmount, explorerAddressUrl } from "@/lib/contracts";
import { getDrawAddress } from "@/lib/draws";
import { readVerification } from "@/lib/verification";

export const metadata: Metadata = { title: "Verify a draw", description: "Independently verify a settled Sortis draw." };

export default async function VerifyPage({ params }: { params: Promise<{ roundId: string }> }) {
  const { roundId: raw } = await params; const roundId = BigInt(raw); const trails = await readVerification(roundId);
  return <main className="section-shell space-y-8"><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Public draw proof</p><h1 className="font-heading text-4xl tracking-tight md:text-5xl">Round {roundId.toString()}</h1><p className="max-w-2xl text-base leading-7 text-muted-foreground">Everything below comes from public event data. No wallet or private key is required.</p></div><div className="grid gap-6 lg:grid-cols-2">{trails.map((trail) => <article key={trail.poolId} className="space-y-5 rounded-xl border bg-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{trail.poolId === "demo" ? "Demo pool" : "Standard pool"}</p><h2 className="mt-2 text-2xl font-medium">{trail.rolledOver ? "Rolled over" : trail.settled ? "Settled" : "Not settled"}</h2></div><a className="font-mono text-xs text-brand hover:underline" href={explorerAddressUrl(getDrawAddress(trail.poolId))} target="_blank" rel="noreferrer">draw contract</a></div>{trail.rolledOver ? <p role="status" className="border-y py-3 text-sm font-medium">No active ticket held the random range. The prize carries forward.</p> : null}<dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-muted-foreground">Tickets frozen</dt><dd className="mt-1 font-mono">{trail.frozenTicketCount?.toString() ?? "-"}</dd></div><div><dt className="text-xs text-muted-foreground">Published total</dt><dd className="mt-1 font-mono">{trail.total?.toString() ?? "-"}</dd></div><div><dt className="text-xs text-muted-foreground">Random value</dt><dd className="mt-1 font-mono">{trail.random?.toString() ?? "-"}</dd></div><div><dt className="text-xs text-muted-foreground">Prize</dt><dd className="mt-1 font-mono">{trail.prize === undefined ? trail.carriedPrize === undefined ? "-" : `${formatTokenAmount(trail.carriedPrize)} cUSDT carried` : `${formatTokenAmount(trail.prize)} cUSDT`}</dd></div></dl><p className="text-xs text-muted-foreground">Close, oracle reveal, random draw, and settlement are indexed directly from the draw engine.</p></article>)}</div></main>;
}
