"use client";

import * as React from "react";
import { Gift, Eye, Sparkles } from "lucide-react";
import { toHex } from "viem";
import { useAccount, usePublicClient, useReadContract, useWalletClient, useWriteContract } from "wagmi";

import { ConnectButton } from "@/components/app/connect-button";
import { EncryptedGate } from "@/components/app/encrypted-gate";
import { useNetworkMismatch } from "@/components/app/network-guard";
import { useFhevm } from "@/components/providers/fhevm-provider";
import { Button } from "@/components/ui/button";
import { explorerTxUrl, formatTokenAmount, sepolia, SEPOLIA_CHAIN_ID, sortisPoolAbi, TOKEN_SYMBOL, type Address } from "@/lib/contracts";
import { getUserDecryptSession } from "@/lib/fhevm/user-decryption";

type PoolId = "demo" | "standard";
const claimAbi = [{ type: "function", name: "claim", stateMutability: "nonpayable", inputs: [{ name: "encryptedAmount", type: "bytes32" }, { name: "inputProof", type: "bytes" }], outputs: [] }] as const;
const zeroHandle = (value?: string) => !value || /^0x0*$/.test(value);

export function PrizesPanel() {
  const { address, isConnected } = useAccount(); const { data: walletClient } = useWalletClient(); const publicClient = usePublicClient({ chainId: SEPOLIA_CHAIN_ID });
  const { instance } = useFhevm(); const wrongNetwork = useNetworkMismatch(); const { writeContractAsync } = useWriteContract();
  const [poolId, setPoolId] = React.useState<PoolId>("demo"); const [amount, setAmount] = React.useState<bigint | null>(null); const [busy, setBusy] = React.useState(false); const [message, setMessage] = React.useState<string | null>(null); const [hash, setHash] = React.useState<`0x${string}` | null>(null);
  const pool = sepolia[poolId].pool as Address;
  const { data: handle, refetch } = useReadContract({ address: pool, abi: sortisPoolAbi, functionName: "claimableHandleOf", args: address ? [address] : undefined, chainId: SEPOLIA_CHAIN_ID, query: { enabled: Boolean(address) } });

  async function reveal() { if (!address || !instance || !walletClient || zeroHandle(handle)) return; setBusy(true); setMessage("Opening your encrypted prize envelope..."); try { const contracts = [sepolia.token as Address, sepolia.demo.pool as Address, sepolia.standard.pool as Address]; const session = await getUserDecryptSession(instance, address, contracts, request => walletClient.signTypedData(request as never)); const result = await instance.userDecrypt([{ handle: handle!, contractAddress: pool }], session.privateKey, session.publicKey, session.signature, contracts, address, session.startTimestamp, session.durationDays); const clear = result[handle!.toLowerCase() as `0x${string}`] ?? result[handle!]; if (typeof clear !== "bigint") throw new Error("The relayer returned an invalid prize."); setAmount(clear); setMessage(clear > 0n ? "You won. Your prize is ready to claim." : "No unclaimed prize in this pool yet. Every participant slot is still privately updated each draw."); } catch (error) { setMessage(error instanceof Error ? error.message.split("\n")[0] : String(error)); } finally { setBusy(false); } }
  async function claim() { if (!address || !instance || !publicClient || !amount || amount <= 0n) return; setBusy(true); setHash(null); setMessage("Encrypting your private claim amount..."); try { const encrypted = await instance.createEncryptedInput(pool, address).add64(amount).encrypt(); const tx = await writeContractAsync({ address: pool, abi: claimAbi, functionName: "claim", args: [toHex(encrypted.handles[0]), toHex(encrypted.inputProof)], chainId: SEPOLIA_CHAIN_ID }); const receipt = await publicClient.waitForTransactionReceipt({ hash: tx }); if (receipt.status !== "success") throw new Error("The claim transaction reverted."); setHash(tx); setAmount(null); setMessage("Prize claimed privately. The confidential tokens are now in your wallet."); await refetch(); } catch (error) { setMessage(error instanceof Error ? error.message.split("\n")[0] : String(error)); } finally { setBusy(false); } }

  return <section className="section-shell space-y-8"><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Private prizes</p><h1 className="max-w-3xl font-heading text-4xl tracking-tight md:text-5xl">Find out without telling everyone else.</h1><p className="max-w-2xl text-base leading-7 text-muted-foreground">Your result stays encrypted. Reveal it privately, then claim confidential tokens without publishing the prize amount.</p></div><div className="flex w-fit rounded-lg border p-1">{(["demo", "standard"] as const).map(id => <button key={id} type="button" onClick={() => { setPoolId(id); setAmount(null); setMessage(null); }} className={`rounded-md px-3 py-2 text-sm ${poolId === id ? "bg-foreground text-background" : "text-muted-foreground"}`}>{id === "demo" ? "Demo pool" : "Standard pool"}</button>)}</div>{!isConnected ? <div className="rounded-xl border bg-card p-6"><p className="mb-4 text-sm text-muted-foreground">Connect your Sepolia wallet to open your prize envelope.</p><ConnectButton /></div> : <div className="mx-auto max-w-2xl rounded-xl border bg-card p-6 text-center sm:p-10"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border bg-background"><Gift className="h-6 w-6 text-brand" /></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Encrypted result</p><div aria-live="polite" className="mt-3 min-h-16">{amount === null ? <p className="font-mono text-4xl tracking-widest">••••••••</p> : amount > 0n ? <p className="font-heading text-5xl text-brand"><Sparkles className="mr-2 inline h-7 w-7" />{formatTokenAmount(amount)} {TOKEN_SYMBOL}</p> : <p className="font-heading text-3xl">Not this round</p>}</div><div className="mt-8 flex justify-center gap-3"><EncryptedGate label="prize decryption" className="w-full max-w-lg text-left"><Button variant="outline" onClick={reveal} loading={busy} disabled={wrongNetwork || zeroHandle(handle)}><Eye className="mr-2 h-4 w-4" />Reveal prize</Button></EncryptedGate>{amount !== null && amount > 0n ? <Button onClick={claim} loading={busy} disabled={wrongNetwork}>Claim prize</Button> : null}</div>{message ? <p role="status" className="mt-6 text-sm text-muted-foreground">{message}</p> : null}{hash ? <a className="mt-2 inline-block font-mono text-xs text-brand hover:underline" href={explorerTxUrl(hash)} target="_blank" rel="noreferrer">View transaction</a> : null}</div>}</section>;
}
