// Generated by packages/contracts/scripts/deploy.ts. Do not edit by hand.

export const SEPOLIA_CHAIN_ID = 11155111;
export const SEPOLIA_EXPLORER = "https://sepolia.etherscan.io";

export type Address = `0x${string}`;

export const sepolia = {
  chainId: SEPOLIA_CHAIN_ID,
  explorer: SEPOLIA_EXPLORER,
  token: "0x485b62eEB1931091FA8bBfb37d1a7B9A18EA345b" as Address,
  faucet: "0xDACEa85f7f8A2F9D80A7278f207C0dFAe16417B0" as Address,
  demo: {
    pool: "0x92aF68E6823D22D5Bd5B8746f1c52b87CE3315aF" as Address,
    draw: "0x89efaA363468478aeB5CAaf80e21680B129F40A6" as Address,
    yieldSource: "0x575Cf61C0FB339D469582fE45219E4bF40e60243" as Address,
    roundDuration: 300,
  },
  standard: {
    pool: "0x1d7E3ED492D6204A25b7B7a0bbE6C9943555395F" as Address,
    draw: "0xD79fAd0748D999e9274470f8F3b64571D9e12240" as Address,
    yieldSource: "0x7B5227267356f91ff2Cb3306C3ee5b6aBa97C421" as Address,
    roundDuration: 86400,
  },
} as const;
