// Generated by packages/contracts/scripts/deploy.ts. Do not edit by hand.

export const SEPOLIA_CHAIN_ID = 11155111;
export const SEPOLIA_EXPLORER = "https://sepolia.etherscan.io";

export type Address = `0x${string}`;

export const sepolia = {
  chainId: SEPOLIA_CHAIN_ID,
  explorer: SEPOLIA_EXPLORER,
  token: "0xd82C37256145dd6554d9090bF679a6c18e0680d1" as Address,
  faucet: "0x954A8e01E67B91e4E11c50DEa7Ac296B47db8d12" as Address,
  demo: {
    pool: "0x80c810c6de816C06DB10ee8d385D36AE485c8B4C" as Address,
    draw: "0x9bF662CAA9F9d5b0d50F0Ee415032558f9118F23" as Address,
    yieldSource: "0x976843b13198E297582577205E46Df9FA931b0Fd" as Address,
    roundDuration: 300,
  },
  standard: {
    pool: "0x536B45dfe74bEd50E3FEF421f67c349B4Be3F77c" as Address,
    draw: "0xDD07755F8027d27C2cbC8F5b6512844118B8D87e" as Address,
    yieldSource: "0x4E614fF0e76c7E9b4f2BD56dE5051d24cad3Cd24" as Address,
    roundDuration: 86400,
  },
} as const;
