// Generated by packages/contracts/scripts/deploy.ts. Do not edit by hand.

export const SEPOLIA_CHAIN_ID = 11155111;
export const SEPOLIA_EXPLORER = "https://sepolia.etherscan.io";

export type Address = `0x${string}`;

export const sepolia = {
  chainId: SEPOLIA_CHAIN_ID,
  explorer: SEPOLIA_EXPLORER,
  token: "0x0E8c04AFd8d4483b0925aF1b4E5a88dde28F0Ff0" as Address,
  faucet: "0x5550e92d4C252763797948Fb751c7116809F7cdb" as Address,
  demo: {
    pool: "0x2238975477e0F90B2084C5C64c61E41fFe7B8F97" as Address,
    draw: "0x30E3eF09C9Ec68bd228f4593382dFF3fe9521E62" as Address,
    yieldSource: "0x7C2dF99d75a14c224d8AD7d24311334f16B92237" as Address,
    roundDuration: 300,
  },
  standard: {
    pool: "0xCCE648f68874F3bf15Bc713a02b8264a2fD0f990" as Address,
    draw: "0x31d445D5A59f74F139926Ccbc56C18ed506ed39e" as Address,
    yieldSource: "0x41E2a43f1Bff35b230686B2B58121eA1CDfb1048" as Address,
    roundDuration: 86400,
  },
} as const;
